# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0003_remove_state_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='process',
        ),
        migrations.RemoveField(
            model_name='activitytarget',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitytarget',
            name='group',
        ),
        migrations.RemoveField(
            model_name='activitytarget',
            name='target',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='user_group',
            new_name='group_member',
        ),
        migrations.RemoveField(
            model_name='request',
            name='email_list',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityTarget',
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
