# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0004_auto_20180627_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontarget',
            name='target',
        ),
        migrations.AddField(
            model_name='actiontarget',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbtest.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
