# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0005_auto_20180628_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Action')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Request')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.User')),
            ],
        ),
    ]
